# Generated by Django 2.0.7 on 2018-08-03 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masal', '0002_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='baglam',
            name='fabl_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='masal.Fabl'),
        ),
    ]
